### ISSUE TITLE
Should use `className` instead of `class`

### ISSUE THREAD

**Issue by malash** [132yse/fard#4]
Should use `className` instead of `class` in `jsx` because `class` is the key work of ES

https://github.com/132yse/fard/blob/bb37aef25e78e6e22420023185213c56fb4238d6/demo/webpack/pages/index/index.js#L9

See https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md

**Comment by 132yse** [comment]
激进点的话，react 也要将 className 换成 class 了
正常点，两个都支持也可以

**Comment by 132yse** [comment]
都支持吧~

**Comment by 132yse** [comment]
都支持吧
```xml
<text class="{{props.class||props.className}}">{{props.nodeValue}}</text>
```

**Comment by 132yse** [comment]
新版支持搞了
