### ISSUE TITLE
webpack-plugin and frrd url 404

### ISSUE THREAD

**Issue by w4ctech** [132yse/fard#6]
![fard-webpack-plugin 404](https://user-images.githubusercontent.com/33955669/60770074-baaa2080-a109-11e9-873d-f60a5dae1e43.png)
[fard-webpack-plugin url 404](https://github.com/132yse/fard/blob/master/tree/master/webpack-plugin)
[fard url 404](https://github.com/132yse/fard/blob/master)

**Comment by 132yse** [comment]
绝望，github 竟然变了路径，之前好好的
